<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.20" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.23.0" />
    <PackageReference Include="NetMQ" Version="4.0.4.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.12" />
  </ItemGroup>
	<ItemGroup>
		<Protobuf Include="Protos/auth.proto" GrpcServices="Server" />
	</ItemGroup>
	<ItemGroup>
		<Protobuf Include="Protos\modbus.proto" GrpcServices="Server" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="EasyModbus">
	    <HintPath>F:\Control Industrial Processes V 1.5.2\Control Industrial Processes\bin\Debug\EasyModbus.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
